from Utilities.config.colors import GLOBAL_COLORS, HOME_COLORS, INPUT_COLORS, RESULTS_COLORS, VISUALIZATION_COLORS, DOCUMENTATION_COLORS, DOWNLOAD_COLORS

COLOR_THEMES = {
    'scientific_blue': {'primary': HOME_COLORS['primary'], 'secondary': HOME_COLORS['secondary'], 'accent': HOME_COLORS['accent'], 'bg_light': HOME_COLORS['lighter'], 'bg_card': HOME_COLORS['light'], 'bg_medium': HOME_COLORS['medium'], 'text': HOME_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': HOME_COLORS['primary'], 'shadow': 'rgba(234, 88, 12, 0.35)', 'border': HOME_COLORS['border']},
    'royal_indigo': {'primary': INPUT_COLORS['primary'], 'secondary': INPUT_COLORS['secondary'], 'accent': INPUT_COLORS['accent'], 'bg_light': INPUT_COLORS['lighter'], 'bg_card': INPUT_COLORS['light'], 'bg_medium': INPUT_COLORS['medium'], 'text': INPUT_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': INPUT_COLORS['primary'], 'shadow': 'rgba(79, 70, 229, 0.35)', 'border': INPUT_COLORS['border']},
    'nature_green': {'primary': DOWNLOAD_COLORS['primary'], 'secondary': DOWNLOAD_COLORS['secondary'], 'accent': DOWNLOAD_COLORS['accent'], 'bg_light': DOWNLOAD_COLORS['lighter'], 'bg_card': DOWNLOAD_COLORS['light'], 'bg_medium': DOWNLOAD_COLORS['medium'], 'text': DOWNLOAD_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': DOWNLOAD_COLORS['primary'], 'shadow': 'rgba(22, 163, 74, 0.35)', 'border': DOWNLOAD_COLORS['border']},
    'genomic_purple': {'primary': RESULTS_COLORS['primary'], 'secondary': RESULTS_COLORS['secondary'], 'accent': RESULTS_COLORS['accent'], 'bg_light': RESULTS_COLORS['lighter'], 'bg_card': RESULTS_COLORS['light'], 'bg_medium': RESULTS_COLORS['medium'], 'text': RESULTS_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': RESULTS_COLORS['primary'], 'shadow': 'rgba(14, 165, 164, 0.35)', 'border': RESULTS_COLORS['border']},
    'emerald_green': {'primary': DOWNLOAD_COLORS['primary'], 'secondary': DOWNLOAD_COLORS['secondary'], 'accent': DOWNLOAD_COLORS['accent'], 'bg_light': DOWNLOAD_COLORS['lighter'], 'bg_card': DOWNLOAD_COLORS['light'], 'bg_medium': DOWNLOAD_COLORS['medium'], 'text': DOWNLOAD_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': DOWNLOAD_COLORS['primary'], 'shadow': 'rgba(22, 163, 74, 0.35)', 'border': DOWNLOAD_COLORS['border']},
    'clinical_teal': {'primary': VISUALIZATION_COLORS['primary'], 'secondary': VISUALIZATION_COLORS['secondary'], 'accent': VISUALIZATION_COLORS['accent'], 'bg_light': VISUALIZATION_COLORS['lighter'], 'bg_card': VISUALIZATION_COLORS['light'], 'bg_medium': VISUALIZATION_COLORS['medium'], 'text': VISUALIZATION_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': VISUALIZATION_COLORS['primary'], 'shadow': 'rgba(0, 229, 255, 0.4)', 'border': VISUALIZATION_COLORS['border']},
    'midnight': {'primary': DOCUMENTATION_COLORS['primary'], 'secondary': DOCUMENTATION_COLORS['secondary'], 'accent': DOCUMENTATION_COLORS['accent'], 'bg_light': DOCUMENTATION_COLORS['lighter'], 'bg_card': DOCUMENTATION_COLORS['light'], 'bg_medium': DOCUMENTATION_COLORS['medium'], 'text': DOCUMENTATION_COLORS['text'], 'tab_bg': GLOBAL_COLORS['neutral_100'], 'tab_active': DOCUMENTATION_COLORS['primary'], 'shadow': 'rgba(185, 28, 28, 0.35)', 'border': DOCUMENTATION_COLORS['border']},
}
TAB_THEMES = {'Home': 'midnight', 'Upload & Analyze': 'royal_indigo', 'Results': 'genomic_purple', 'Download': 'emerald_green', 'Documentation': 'scientific_blue'}
