"""
┌──────────────────────────────────────────────────────────────────────────────┐
│ Documentation Page - Scientific Documentation & References                    │
├──────────────────────────────────────────────────────────────────────────────┤
│ Author: Dr. Venkata Rajesh Yella | License: MIT | Version: 2024.1            │
└──────────────────────────────────────────────────────────────────────────────┘
"""
# ═══════════════════════════════════════════════════════════════════════════════
# IMPORTS
# ═══════════════════════════════════════════════════════════════════════════════
import streamlit as st
import pandas as pd
from Utilities.config.text import UI_TEXT
from Utilities.config.themes import TAB_THEMES
from Utilities.config.colors import UNIFIED_MOTIF_COLORS, MOTIF_CLASS_INFO
from UI.css import load_css
from UI.headers import render_section_heading

# ═══════════════════════════════════════════════════════════════════════════════
# TUNABLE PARAMETERS
# ═══════════════════════════════════════════════════════════════════════════════
MOTIF_PARAMETERS = {"Curved DNA": {"min_length": "20 bp", "max_length": "500 bp", "algorithm": "A-tract phasing detection", "scoring": "Tract length × phasing score", "refs": ["Crothers et al., 1990", "Koo et al., 1986"]}, "G-Quadruplex": {"min_length": "15 bp", "max_length": "100 bp", "algorithm": "G4Hunter + Regex pattern matching", "scoring": "G4Hunter score (threshold ≥1.2)", "refs": ["Bedrat et al., 2016", "Huppert & Balasubramanian, 2005"]}, "Z-DNA": {"min_length": "8 bp", "max_length": "200 bp", "algorithm": "Alternating purine-pyrimidine detection", "scoring": "Z-score with GC enrichment", "refs": ["Ho et al., 1986", "Wang et al., 1979"]}, "Cruciform": {"min_length": "10 bp arm", "max_length": "100 bp arm", "algorithm": "Inverted repeat detection", "scoring": "Arm length × stem stability", "refs": ["Lilley, 1980", "Panayotatos & Wells, 1981"]}, "R-Loop": {"min_length": "15 bp", "max_length": "2000 bp", "algorithm": "QmRLFS model", "scoring": "Thermodynamic ΔG stability", "refs": ["Jenjaroenpun et al., 2015", "Aguilera & García-Muse, 2012"]}, "Triplex": {"min_length": "10 bp", "max_length": "100 bp", "algorithm": "Mirror repeat detection", "scoring": "Purine/pyrimidine purity ≥90%", "refs": ["Mirkin et al., 1987", "Frank-Kamenetskii & Mirkin, 1995"]}, "i-Motif": {"min_length": "12 bp", "max_length": "60 bp", "algorithm": "C-tract pattern matching", "scoring": "C-run count × content score", "refs": ["Zeraati et al., 2018", "Day et al., 2014"]}, "Slipped DNA": {"min_length": "6 bp unit", "max_length": "50 bp unit", "algorithm": "Direct repeat detection", "scoring": "Unit copies × repeat fidelity", "refs": ["Pearson et al., 2005", "Wells, 2007"]}, "A-philic DNA": {"min_length": "10 bp", "max_length": "200 bp", "algorithm": "Tetranucleotide log₂ odds scoring", "scoring": "Propensity score threshold", "refs": ["Vinogradov, 2003", "Rohs et al., 2009"]}}
REFERENCES = [{"authors": "Bedrat A, Lacroix L, Mergny JL", "year": 2016, "title": "Re-evaluation of G-quadruplex propensity with G4Hunter", "journal": "Nucleic Acids Res", "volume": "44(4):1746-59", "doi": "10.1093/nar/gkw006"}, {"authors": "Huppert JL, Balasubramanian S", "year": 2005, "title": "Prevalence of quadruplexes in the human genome", "journal": "Nucleic Acids Res", "volume": "33(9):2908-16", "doi": "10.1093/nar/gki609"}, {"authors": "Zeraati M, Langley DB, et al.", "year": 2018, "title": "I-motif DNA structures are formed in the nuclei of human cells", "journal": "Nat Chem", "volume": "10(6):631-637", "doi": "10.1038/s41557-018-0046-3"}, {"authors": "Ho PS, Frederick CA, Saal D, et al.", "year": 1986, "title": "The interactions of ruthenium hexaammine with Z-DNA", "journal": "J Biomol Struct Dyn", "volume": "4(3):521-34", "doi": "10.1080/07391102.1986.10506363"}, {"authors": "Jenjaroenpun P, Wongsurawat T, et al.", "year": 2015, "title": "QmRLFS-finder: a model, web server and stand-alone tool", "journal": "Nucleic Acids Res", "volume": "43(W1):W527-34", "doi": "10.1093/nar/gkv344"}, {"authors": "Aguilera A, García-Muse T", "year": 2012, "title": "R loops: from transcription byproducts to threats to genome stability", "journal": "Mol Cell", "volume": "46(2):115-24", "doi": "10.1016/j.molcel.2012.04.009"}, {"authors": "Frank-Kamenetskii MD, Mirkin SM", "year": 1995, "title": "Triplex DNA structures", "journal": "Annu Rev Biochem", "volume": "64:65-95", "doi": "10.1146/annurev.bi.64.070195.000433"}, {"authors": "Crothers DM, Drak J, et al.", "year": 1990, "title": "DNA bending, flexibility, and helical repeat", "journal": "Methods Enzymol", "volume": "212:3-29", "doi": "10.1016/0076-6879(92)12003-9"}, {"authors": "Vinogradov AE", "year": 2003, "title": "DNA helix: the importance of being GC-rich", "journal": "Nucleic Acids Res", "volume": "31(7):1838-44", "doi": "10.1093/nar/gkg296"}, {"authors": "Rohs R, West SM, et al.", "year": 2009, "title": "The role of DNA shape in protein-DNA recognition", "journal": "Nature", "volume": "461(7268):1248-53", "doi": "10.1038/nature08473"}, {"authors": "Pearson CE, Nichol Edamura K, Cleary JD", "year": 2005, "title": "Repeat instability: mechanisms of dynamic mutations", "journal": "Nat Rev Genet", "volume": "6(10):729-42", "doi": "10.1038/nrg1689"}, {"authors": "Bacolla A, Wells RD", "year": 2004, "title": "Non-B DNA conformations, genomic rearrangements, and human disease", "journal": "J Biol Chem", "volume": "279(46):47411-4", "doi": "10.1074/jbc.R400028200"}]
MOTIF_DESCRIPTIONS = {'Curved_DNA': "Intrinsic DNA curvature from phased A-tracts", 'Slipped_DNA': "Slippage-mediated repeat expansions", 'Cruciform': "Hairpin structures from palindromic sequences", 'R-Loop': "Co-transcriptional R-loop formation sites", 'Triplex': "Triple-stranded DNA from mirror repeats", 'G-Quadruplex': "Four-stranded G-rich secondary structures", 'i-Motif': "Intercalated cytosine structures", 'Z-DNA': "Alternating purine-pyrimidine sequences", 'A-philic_DNA': "High nucleosome positioning potential", 'Hybrid': "Regions with multiple motif types", 'Non-B_DNA_Clusters': "High-density Non-B DNA regions"}
# ═══════════════════════════════════════════════════════════════════════════════

def _build_motif_card(n, sub, col, desc): return f"<div style='background:white;padding:0.7rem;border-radius:10px;box-shadow:0 2px 8px rgba(0,0,0,0.06);border-left:4px solid {col};'><strong style='color:#1e293b;font-size:0.85rem;'>{n}</strong><div style='color:{col};font-size:0.7rem;font-weight:600;margin:0.15rem 0;'>{sub}</div><div style='color:#64748b;font-size:0.7rem;line-height:1.3;'>{desc}</div></div>"
def _build_reference_card(r): return f"<div style='background:#f8fafc;padding:0.5rem;border-radius:6px;border-left:3px solid #3b82f6;'><div style='font-weight:600;color:#1e293b;font-size:0.75rem;margin-bottom:0.15rem;'>{r['authors']} ({r['year']})</div><div style='color:#334155;font-size:0.7rem;font-style:italic;margin-bottom:0.1rem;'>{r['title']}</div><div style='color:#64748b;font-size:0.65rem;'><strong>{r['journal']}</strong> {r['volume']} · <a href=\"https://doi.org/{r['doi']}\" target=\"_blank\" style=\"color:#3b82f6;\">DOI: {r['doi']}</a></div></div>"

def _render_materials_and_methods():
    """Render the Materials and Methods section as an expandable panel."""
    with st.expander("📄 Materials and Methods", expanded=False):
        st.markdown(
            """
<div style='font-family:Georgia,serif;line-height:1.7;color:#1e293b;font-size:0.88rem;'>

<h2 style='color:#1e40af;font-size:1.1rem;border-bottom:2px solid #1e40af;padding-bottom:0.3rem;margin-top:0;'>Materials and Methods</h2>

<h3 style='color:#1e40af;font-size:1rem;margin-top:1.2rem;'>2.1 System Architecture and Workflow</h3>
<p>NBDFinder is a two-layer computational framework designed for genome-scale detection and integration of non-B DNA–forming sequence motifs. The backend consists of nine modular Python-based detector classes — covering Curved DNA, Slipped DNA, Cruciform DNA, Triplex DNA, R-loops, Z-DNA, G-Quadruplex, i-Motif, and A-philic DNA — each implementing biologically informed regular expressions, compositional heuristics, and propensity-based scoring models. The frontend is implemented using the Streamlit framework and supports sequence submission, parameter selection, execution, visualization, and export. Two integrative post-processing stages — hybrid-region annotation and density-based cluster identification — operate across the outputs of all nine primary detectors.</p>
<p>Input sequences may be provided as FASTA files, direct nucleotide strings, or retrieved programmatically from NCBI using Biopython (Entrez and SeqIO modules). Upon ingestion, sequences are normalized to uppercase, header lines are removed, and non-ATGC characters are filtered; all downstream composition calculations are performed exclusively on the resulting canonical base set. GC percentage is accordingly computed as (G + C) / (A + T + G + C) × 100, matching the NCBI and Ensembl standard by excluding ambiguous bases from both the numerator and the denominator. All coordinates are reported using 1-based inclusive indexing.</p>
<p>The analytical workflow consists of: (i) sequence preprocessing and validation; (ii) primary detection of canonical motifs; (iii) detection of relaxed or variant subclasses; (iv) class-specific scoring and normalization; (v) intra-class overlap resolution; (vi) inter-class hybrid detection; (vii) density-based hotspot identification; and (viii) structured output generation. For sequences shorter than 100,000 bp, analysis proceeds directly using all detectors in a single pass. Sequences between 100,000 bp and 5,000,000 bp are processed using a two-worker ProcessPoolExecutor with 50 kb chunks and 2 kb overlaps. Sequences exceeding 5,000,000 bp are handled by a disk-streaming strategy that maintains approximately constant RAM usage (~70 MB) regardless of genome size.</p>

<h3 style='color:#1e40af;font-size:1rem;margin-top:1.2rem;'>2.2 Motif Library and Structural Classification</h3>
<p>The motif library was curated through systematic literature review and organized into nine principal structural detector classes, each with biologically supported subclasses: Curved DNA (global and local curvature subtypes), Slipped DNA (short tandem repeats and direct repeats), Cruciform DNA (palindromic inverted repeats), Triplex DNA (H-DNA mirror repeats and Sticky DNA), R-loops (promoter-proximal RNA–DNA hybrid formation sites), Z-DNA (left-handed helix and extruded-G Z-DNA motifs), G-Quadruplex (eight subclasses ranging from telomeric repeats to G-triplexes), i-Motif (canonical cytosine-intercalated structures and AC-motifs), and A-philic DNA (A-form propensity regions). Two integrative classes — hybrid motifs (overlapping multi-class intervals) and non-B DNA clusters (high-density structural hotspots) — are derived from the primary detector outputs. Disease-associated repeat expansions were incorporated where experimentally validated structural consequences have been reported.</p>

<h3 style='color:#1e40af;font-size:1rem;margin-top:1.2rem;'>2.3 Motif Detection Algorithms</h3>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.1 Curved DNA</h4>
<p>Curvature-prone regions were identified by a two-stage A/T-tract analysis. In the first stage, all contiguous runs of A and T bases meeting a minimum length of 3 bp are enumerated. Each candidate window is analyzed on both strands to determine the dominant A-tract center position using a sliding algorithm that tracks A-run length, T-run length, and AT/TA transition states. Only windows where the longest A-rich run exceeds the longest T-only run by at least 3 nt are retained as called tract centers, and a fractional center position is computed for each.</p>
<p>In the second stage, called centers are grouped into A-phased repeats (APRs) by requiring at least three consecutive centers with helical-phasing spacing between 9.9 and 11.1 bp (reference spacing 11.0 bp, approximating the B-DNA helical repeat). A phasing score is computed as 1 − (mean deviation from ideal spacing / maximum allowed deviation), rewarding tighter helical periodicity. Separately, long isolated A-tracts or T-tracts of at least 7 bp are identified as local curvature motifs. Their scores are computed as L/(L + 6), saturating asymptotically toward 1.0 with increasing tract length. All raw scores are normalized linearly to a 1.0–3.0 confidence scale bounded by empirically defined floor (0.1) and ceiling (0.95) values.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.2 Slipped DNA and Tandem Repeats</h4>
<p>Direct repeats and short tandem repeats (STRs) were identified as tandemly arrayed sequence units using Python regular expressions compiled with a per-unit-size pattern cache. STRs were defined using core parameters as repeat units of 1–4 nt occurring at least 6 times consecutively, and under relaxed parameters as units of 1–6 nt occurring at least 4 times. Direct repeats were defined as repeat units of 7–50 nt occurring at least 2 times, with a minimum total tract length of 20 bp. The boundary between STR and direct repeat classification is set at a unit length threshold of 7 nt. Low-complexity artifacts were filtered using Shannon entropy computed over A, T, G, and C base frequencies, with a minimum threshold of 0.5 bits. Scores are computed by a piecewise mechanistic model integrating JIT-compiled functions for tract length, copy number, unit size, base purity, and GC fraction, normalized linearly to the 1.0–3.0 confidence scale.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.3 Cruciform-Forming Inverted Repeats</h4>
<p>Cruciform motifs were detected via a seed-and-extend algorithm applied to inverted repeat pairs. An initial 6-mer seed index is constructed over the sequence; for each seed hit, the reverse complement arm is located and extended bidirectionally until a mismatch is encountered or arm length limits are reached. Arm lengths between 8 and 50 bp with spacer loops up to 12 bp and zero mismatches are retained. Thermodynamic stability is assessed using a nearest-neighbor energy model (SantaLucia 1998) with parameters covering all 16 dinucleotide steps, and only inverted repeats with predicted ΔG ≤ −5.0 kcal/mol are reported. Scoring integrates arm length, symmetry, and GC content, and is normalized to the 1.0–3.0 confidence scale using linear interpolation between raw score floor 0.5 and ceiling 0.95.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.4 Triplex and Sticky DNA</h4>
<p>Triplex-forming mirror repeats were detected as homopurine or homopyrimidine mirror sequences with arm lengths of 10–100 bp and spacer tolerance up to 8 bp, requiring a purine or pyrimidine fraction of at least 0.90. A JIT-compiled purity calculation determines whether each candidate arm meets the strand-purity threshold. The H-DNA scoring model integrates arm length relative to a 35 bp reference, a loop penalty term modulated by a 0.4 exponent on spacer length, a purity weight (0.30), an arm-length weight (0.35), a loop weight (0.20), and an interruption penalty weight (0.15). Raw scores are normalized linearly to the 1.0–3.0 confidence scale using floor 0.5 and ceiling 0.95.</p>
<p>Sticky DNA was operationalized as uninterrupted (GAA)n or (TTC)n tracts using a piecewise linear scoring model calibrated to three biological thresholds: a replication-blockage threshold (≥20 copies, base score 1.3), a stable-formation threshold (≥40 copies, base score 2.0), and a pathogenic-expansion threshold (≥60 copies, base score 2.6). These cutoffs are consistent with clinical Friedreich's ataxia expansion thresholds reported in the literature.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.5 R-Loop–Forming Sequences</h4>
<p>R-loop prediction followed a two-stage framework adapted from the QmRLFS model (Jenjaroenpun et al. 2015, 2016). In the first stage, initiation zones (R-loop initiation zones, RIZ) are identified as regions where G-run–enriched patterns match either of two models: Model 1 captures G{3+} clusters separated by up to 10 intervening bases, while Model 2 captures denser G{4+} tracts. A guanine content threshold of ≥50% is required for RIZ candidacy. In the second stage, each valid RIZ is extended downstream into a GC-rich elongation zone (REZ) of up to 2,000 bp, requiring a GC content of at least 40% across the combined region. Final R-loop scores integrate GC content and G-run density across both zones and are normalized linearly to the 1.0–3.0 confidence scale.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.6 Z-DNA and eGZ Motifs</h4>
<p>Z-DNA propensity was estimated using a precomputed 10-mer scoring table derived from the dinucleotide propensity matrix of Ho et al. (1986), which assigns higher scores to CG, GC, AC, and GT dinucleotide steps. All exact 10-mer matches in the query sequence are located using either the Hyperscan high-performance regex engine (when available) or a pure-Python sliding-window fallback. Matched 10-mers are merged if they are adjacent or overlapping, and per-base contributions are aggregated by distributing each 10-mer score uniformly across its ten positions, optionally using NumPy vectorization for sequences longer than 1,000 bp. Merged regions must exceed a cumulative sum score threshold (default 50.0) and contain at least one contributing 10-mer to be reported. Scores are normalized using a log-linear scale between raw floor 50.0 and ceiling 2,000.0.</p>
<p>Extruded-G Z-DNA (eGZ) motifs were independently detected as trinucleotide repeats of CGG, GGC, CCG, or GCC with at least 4 consecutive copies, consistent with the structural model of Herbert (1997). Each eGZ repeat is scored proportionally to repeat count relative to the minimum threshold and annotated for association with disease-relevant CGG/CCG expansions (Fragile X syndrome) when copy numbers exceed established clinical cutoffs.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.7 G-Quadruplex Family</h4>
<p>Canonical G4 motifs were identified using the pattern G{3+}N{1–7}G{3+}N{1–7}G{3+}N{1–7}G{3+}. Additional detectors captured telomeric repeats ((TTAGGG){4+}), extended-loop G4s (loops 1–12 nt), bulged G4s (G-tracts containing a single-nucleotide internal bulge), higher-order G4 arrays and G-wires (seven or more consecutive G-tract repeats), stacked multi-quadruplex assemblies (two or more canonical G4 units separated by up to 20 bp linkers), G-triplex intermediates (three G-runs), and weak PQS motifs (four G-runs of at least 2 G each).</p>
<p>Detection proceeds via a seeded scanning strategy: all G{3+} positions are first located, adjacent seed windows are merged into contiguous scan regions to eliminate redundant processing in GC-rich stretches, and each pattern is matched only within those regions. Each candidate is scored using a G-only sliding-window G4Hunter algorithm (window size 25 nt by default), computing the maximum normalized G density and scaling it by the region length relative to the window size. Numba JIT compilation is applied to the sliding-window maximum subarray function for sequences exceeding 50 bp. Overlap resolution retains the highest-scoring representative from each genomic interval, with priority assigned in the order: telomeric > higher-order > stacked > canonical > bulged > extended-loop > G-triplex > weak PQS.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.8 i-Motif and AC-Motif Detection</h4>
<p>i-motifs were defined as sequences containing four or more cytosine tracts, each consisting of at least 3 consecutive cytosines, separated by 1–7 nt loops, matching the pattern C{3+}N{1–7}C{3+}N{1–7}C{3+}N{1–7}C{3+}. Scores integrate C-run density, cytosine fraction, and loop compactness. Canonical subclasses with short loops (1–7 nt) are distinguished from long-loop variants during subclass assignment. AC-motifs were identified via phased alternating A-tract and C-tract consensus patterns as described by Hur et al. (2021), covering spacer lengths of 4, 5, and 6 bp between tract anchors, and reported qualitatively with separate pattern identifiers. Overlap resolution retains canonical i-motifs over AC-motifs when both patterns share the same genomic interval.</p>

<h4 style='color:#334155;font-size:0.95rem;margin-top:1rem;'>2.3.9 A-Philic DNA Propensity Modeling</h4>
<p>A-philic DNA propensity was estimated using a precomputed 10-mer scoring table of log₂ enrichment values derived from A-form and B-form DNA crystal structures in the Nucleic Acid Knowledgebase. Only canonical ATGC sequences were retained; tetranucleotide step frequencies were stratified by conformational class, and signed propensity scores were computed as log₂ odds ratios with pseudocount 0.5. The scoring table covers all possible 10-mer sequences with positive A-form propensity. Detection proceeds by locating all exact 10-mer matches using the same Hyperscan or pure-Python fallback used for Z-DNA, accumulating per-base contributions from each matching 10-mer into a per-position score array (optionally vectorized with NumPy), and merging adjacent high-scoring segments into contiguous A-philic regions. A minimum cumulative log₂ sum threshold of 0.5 is applied. Raw scores are normalized linearly to the 1.0–3.0 confidence scale.</p>

<h3 style='color:#1e40af;font-size:1rem;margin-top:1.2rem;'>2.4 Hybrid Motifs and Cluster Detection</h3>
<p>Hybrid regions were defined as genomic intervals where two or more distinct motif classes overlapped. Two motifs from different classes are considered overlapping when their shared bases constitute at least 50% of the length of the shorter interval (HYBRID_MIN_OVERLAP = 0.50). Overlapping pairs are merged into a single hybrid annotation that records all contributing class labels and is assigned a composite diversity-weighted overlap score proportional to the number of contributing classes.</p>
<p>Structural hotspots (clusters) were identified by sliding a 300 bp window across the sequence in single-base steps and counting overlapping motif calls from any class within each window position. Windows containing at least 4 total motifs from at least 3 unique structural classes were recorded as cluster candidates and merged when adjacent. Each reported cluster is annotated with its genomic span, total motif count, class diversity, and a density score reflecting motifs per kilobase.</p>

<h3 style='color:#1e40af;font-size:1rem;margin-top:1.2rem;'>2.5 Algorithmic Optimization and Statistical Controls</h3>
<p>Motif scanning for Z-DNA and A-philic DNA was accelerated using Hyperscan (Intel's high-performance regular expression engine), which provides linear-time exact-string matching over large 10-mer pattern sets via compiled automata. When Hyperscan is unavailable, a pure-Python sliding-window fallback is invoked transparently. For G-Quadruplex, Triplex, and Slipped DNA detection, computationally intensive scoring kernels (sliding-window maximum subarray, purity calculation, slippage base score) are compiled using Numba just-in-time (JIT) compilation with caching, providing 2–5× speedup over interpreted Python on the hot path. NumPy vectorization is applied to per-base contribution array construction for Z-DNA and A-philic DNA for sequences longer than 1,000 bp.</p>
<p>For multi-detector execution, sequences exceeding 50,000 bp are analyzed using a ThreadPoolExecutor with up to nine concurrent worker threads (one per detector type), yielding a 1.5–2× throughput improvement on multi-core hardware. All motif calls are validated for minimum length, length normalization, and GC composition adjustment. Shannon entropy (minimum 0.5 bits for Slipped DNA) is applied to filter low-complexity artifacts. Scores are normalized to a universal 1.0–3.0 confidence scale using class-specific raw score bounds, enabling cross-class comparison.</p>

<h3 style='color:#1e40af;font-size:1rem;margin-top:1.2rem;'>2.6 Output Structure and Implementation</h3>
<p>For each sequence, NBDFinder reports a tabular record for every detected motif containing: motif coordinates (Start, End, Length), subclass label, class-specific score, pattern identifier, strand orientation, detection method, and class-specific supplementary fields such as G-tract counts and loop lengths for G-Quadruplex, arm length and thermodynamic stability for Cruciform, repeat unit and copy count for Slipped DNA, and GC skew metrics for R-loops. Per-class counts and motif coverage fractions are summarized in a companion statistics table. Outputs are available in CSV and XLSX formats and include summary statistics and visualization-ready annotations compatible with the integrated Streamlit visualization pipeline (Manhattan plots, density heatmaps, circos-style diagrams).</p>
<p>The platform is implemented in Python 3 using pandas, NumPy, matplotlib, seaborn, and the regex library. Optional acceleration dependencies include Numba (≥0.56.0) for JIT compilation, Hyperscan for high-performance pattern matching, and PyFastx for accelerated FASTA parsing. The application is open-source and available at <a href="https://github.com/VRYella/NonBDNAFinder" target="_blank" style="color:#1e40af;">https://github.com/VRYella/NonBDNAFinder</a>.</p>

</div>
""",
            unsafe_allow_html=True,
        )


def render():
    load_css(TAB_THEMES.get('Documentation', 'scientific_blue')); render_section_heading("Scientific Documentation & References", page="Documentation")
    st.markdown("<div style='background:linear-gradient(135deg,#1e40af 0%,#7c3aed 100%);padding:1rem;border-radius:12px;margin-bottom:1rem;box-shadow:0 4px 16px rgba(30,64,175,0.3);'><h2 style='color:white;margin:0 0 0.5rem 0;font-size:1.2rem;font-weight:700;'>NonBDNAFinder v2025.1</h2><p style='color:rgba(255,255,255,0.95);font-size:0.85rem;line-height:1.4;margin:0;'>Comprehensive platform for <strong>genome-wide detection</strong> of Non-B DNA structures. Implements <strong>11 motif classes</strong> with <strong>24 subclasses</strong>, validated against G4Hunter, QmRLFS, and Z-Seeker.</p><div style='display:flex;gap:0.5rem;margin-top:0.6rem;flex-wrap:wrap;'><span style='background:rgba(255,255,255,0.2);padding:0.25rem 0.6rem;border-radius:16px;color:white;font-size:0.7rem;font-weight:600;'>24,674 bp/s</span><span style='background:rgba(255,255,255,0.2);padding:0.25rem 0.6rem;border-radius:16px;color:white;font-size:0.7rem;font-weight:600;'>200MB+ sequences</span><span style='background:rgba(255,255,255,0.2);padding:0.25rem 0.6rem;border-radius:16px;color:white;font-size:0.7rem;font-weight:600;'>25+ visualizations</span><span style='background:rgba(255,255,255,0.2);padding:0.25rem 0.6rem;border-radius:16px;color:white;font-size:0.7rem;font-weight:600;'>Nature-ready output</span></div></div>", unsafe_allow_html=True)
    _render_materials_and_methods()
    st.markdown("<h3 style='color:#003D82;font-size:1.1rem;margin:1rem 0 0.5rem 0;font-weight:700;border-left:4px solid #0091FF;padding-left:0.75rem;'>Detected Non-B DNA Motif Classes</h3>", unsafe_allow_html=True)
    cards_html = '<div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(250px,1fr));gap:0.5rem;margin-bottom:1rem;">'
    for info in MOTIF_CLASS_INFO: cards_html += _build_motif_card(info['name'], info['subtitle'], UNIFIED_MOTIF_COLORS[info['key']], MOTIF_DESCRIPTIONS.get(info['key'], info['subtitle']))
    cards_html += '</div>'; st.markdown(cards_html, unsafe_allow_html=True)
    st.markdown("<h3 style='color:#003D82;font-size:1.1rem;margin:1rem 0 0.5rem 0;font-weight:700;border-left:4px solid #0091FF;padding-left:0.75rem;'>Detection Parameters & Algorithms</h3>", unsafe_allow_html=True)
    params_data = [{"Motif Class": m, "Min Length": p["min_length"], "Max Length": p["max_length"], "Algorithm": p["algorithm"], "Scoring Method": p["scoring"]} for m, p in MOTIF_PARAMETERS.items()]
    st.dataframe(pd.DataFrame(params_data), use_container_width=True, hide_index=True, column_config={"Motif Class": st.column_config.TextColumn("Motif Class", width="medium"), "Min Length": st.column_config.TextColumn("Min Length", width="small"), "Max Length": st.column_config.TextColumn("Max Length", width="small"), "Algorithm": st.column_config.TextColumn("Algorithm", width="large"), "Scoring Method": st.column_config.TextColumn("Scoring", width="medium")})
    st.markdown("<h3 style='color:#003D82;font-size:1.1rem;margin:1rem 0 0.5rem 0;font-weight:700;border-left:4px solid #0091FF;padding-left:0.75rem;'>Peer-Reviewed References</h3><p style='color:#64748b;font-size:0.75rem;margin-bottom:0.5rem;'>NonBDNAFinder implements algorithms validated in peer-reviewed publications:</p>", unsafe_allow_html=True)
    refs_html = '<div style="display:flex;flex-direction:column;gap:0.35rem;">' + ''.join(_build_reference_card(r) for r in REFERENCES) + '</div>'; st.markdown(refs_html, unsafe_allow_html=True)
    st.markdown(f"<div style='background:linear-gradient(135deg,#f0f9ff 0%,#e0f2fe 100%);padding:1rem;border-radius:12px;margin-top:1rem;border:1px solid #bae6fd;'><h3 style='color:#0c4a6e;margin:0 0 0.5rem 0;font-size:1rem;font-weight:700;'>How to Cite</h3><div style='background:white;padding:0.7rem;border-radius:6px;font-family:\"Courier New\",monospace;font-size:0.7rem;line-height:1.4;color:#334155;border-left:4px solid #0284c7;'><strong>Yella VR</strong> (2025). NonBDNAFinder: Comprehensive Detection and Analysis of Non-B DNA Forming Motifs.<br>GitHub: <a href=\"https://github.com/VRYella/NonBDNAFinder\" style=\"color:#0284c7;\">https://github.com/VRYella/NonBDNAFinder</a></div><div style='margin-top:0.7rem;padding-top:0.7rem;border-top:1px solid #bae6fd;'><div style='font-weight:700;color:#0c4a6e;font-size:0.8rem;margin-bottom:0.25rem;'>Developed by</div><div style='color:#334155;font-size:0.75rem;'><strong>{UI_TEXT['author']}</strong><br>Email: <a href='mailto:{UI_TEXT['author_email']}' style='color:#0284c7;'>{UI_TEXT['author_email']}</a><br><a href='https://github.com/VRYella' target='_blank' style='color:#0284c7;'>GitHub: VRYella</a></div></div></div>", unsafe_allow_html=True)
